version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd course-service
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - user-service/**
  discard-paths: yes

# Deploy to Lambda function
deploy:
  provider: Lambda
  function-name: curio-mind_course_dev
  region: us-east-1
  role: arn:aws:lambda:us-east-1:5761265890:function:curio-mind_dev
  runtime: nodejs16.x
  timeout: 30
  handler: course-service/lambda.handler
  zip: ./package.zip
